### ISSUE TITLE
Minimum balance of sender account

### ISSUE THREAD

**Issue by Mingyang-Li** [w3f/polkadot-payouts#38]
I followed every step from the instructions and everything went fine until `yarn start`. I began getting connection failed errors. 

**The objective:** To get all payout information given a block hash. 

**What I tried:**
1. In `main.yaml`, I set `minimumSenderBalance` to a super low number trying to allow people with any number of balance to be able to carry out transactions.
2. In `main.yaml`, set `remaining` to 0 so user can freely transact any amount.

Error:
![image](https://user-images.githubusercontent.com/53138432/122700303-1fcb9200-d29f-11eb-80d0-d7853fdae2d9.png)

**About me:** I'm fairly new to Polkadot / Blockchain development as a whole. I've been reading Polkadot wiki and articles and watching tutorials on Polkadot over the past week, but I'm still confused by all the buzz words like staking, nominator, validator, extrinsics, etc. What's the minimal knowledge I need to achieve the objective mentioned above?

**Comment by ironoa** [comment]
Hi @Mingyang-Li, the Polkadot wiki is the perfect starting point to learn. 
The polakdot-payout tool provides these functionalities: https://github.com/w3f/polkadot-payouts#features

Regarding your error: the tool must be connected with a blockchain node to make it scrape the data from the chain... I see you have set ws://localhost:11000 but I assume you don't have a node running and synced on your local machine...
You can configure a well known public node such as wss://kusama-rpc.polkadot.io or wss://rpc.polkadot.io

If you run the tool just with `yarn start` it will take the default config file from `config/main.yaml`
Try either to run it with `yarn start -c pathToMyConfig` or override the default `config/main.yaml`, as it is explained here: https://github.com/w3f/polkadot-payouts#how-it-works
