### ISSUE TITLE
Script should reconnect on closed connection and continue with payouts

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-payouts#42]
When you have many addresses specified in the config script, for which it takes multiple hours to claim all rewards, there's a high chance the remote RPC node will close the connection. When such a disconnection happens, the script should reconnect and **continue with the next address of where it left off**.

Currently, you have to restart the script manually, which will start processing the addresses from the very beginning.

**Comment by ironoa** [comment]
The behavior now looks like this:
![image](https://user-images.githubusercontent.com/25957738/135463908-07eff470-694b-4379-8679-db8f209a3856.png)

**Comment by lamafab** [comment]
Will test this later today.
