### ISSUE TITLE
Error: Unable to decode using the supplied passphrase Polkadot.js wallet

### ISSUE THREAD

**Issue by Natary2021** [w3f/polkadot-payouts#46]
Hi, I wanted to make a transfer using my polkadot Wallet - but It just wont accept my password. And I am pretty sure its the right one. So I recovered everything with JSON File.. and seed words several times.. in order to change my password. But it still doesnt accept my password when doing a transaction. I updated the metadata also. I keep on getting this error in the browser extention: Unable to decode using the supplied passphrase.

Can someone help me? Thx!

**Comment by Nexus2k** [comment]
Have you stored the password w/o a line break? e.g. `echo -n "mySupersecretPassword" > password`

**Comment by Natary2021** [comment]
I managed to solve it.. had this issue a month ago...
Best
Nathalie

Am Fr., 3. Dez. 2021 um 14:41 Uhr schrieb Philipp D. <
***@***.***>:
